package hr.fer.zemris.graphicsOperators;

public enum EMatrixType {
	TRANSLATION, ROTATION_X, ROTATION_Y, ROTATION_Z, SHEAR_MATRIX, SCALING, Z_PARALLEL_PROJECTION, Z_PERSPECTIVE_PROJECTION, LOOK_AT_MATRIX, FRUSTUM_MATRIX
}
